### ISSUE TITLE
code in directory ...\github.com\uber-go\zap expects import "go.uber.org/zap

### ISSUE THREAD

**Issue by SmileEye** [bahlo/go-styleguide#7]
Hi：
 when i try to run this snippet (Structured logging):

<pre><code>
import "github.com/uber-go/zap"
//...
logger, _ := zap.NewProduction()
defer logger.Sync()
logger.Info("Server started",
        zap.Int("port", port),
        zap.String("env", env),
)
</code></pre>

console output:

`main.go:6:2: code in directory D:\golang\src\github.com\uber-go\zap expects import "go.uber.org/zap"
`

I changed "import github.com/uber-go/zap" to"import go.uber.org/zap" and then the result is right . 

Best regards!

jinkun

**Comment by bahlo** [comment]
Hey @SmileEye, sorry for replying so late. You're right, uber uses a custom domain (even though it's an [antipattern](https://github.com/bahlo/go-styleguide#avoid-gopkgin)), so you're forced to use that.
But since the example got replaced with [logrus](https://github.com/Sirupsen/logrus) I will close this. Thanks anyway 👍🏻
